$ErrorActionPreference = "SilentlyContinue"

Write-Host "Limpiando archivos de npm..."
Remove-Item -Force "package-lock.json"
Remove-Item -Force "frontend\package-lock.json"
Remove-Item -Force "frontend\pnpm-workspace.yaml"
Remove-Item -Force "server\pnpm-workspace.yaml"
Remove-Item -Recurse -Force "node_modules"
Remove-Item -Recurse -Force "frontend\node_modules"
Remove-Item -Recurse -Force "server\node_modules"

Write-Host "¡Limpieza completada con éxito!"
Write-Host ""
Write-Host "Ahora debes instalar las dependencias con pnpm. Ejecuta los siguientes comandos uno por uno:"
Write-Host "------------------------------------------------------"
Write-Host "pnpm install"
Write-Host "cd frontend; pnpm install; cd .."
Write-Host "cd server; pnpm install; cd .."
Write-Host "------------------------------------------------------"
